services:
  apache:
    image: owncloudci/php:7.4
    environment:
      APACHE_WEBROOT: /var/www/owncloud
      APACHE_CONFIG_TEMPLATE: ssl
      APACHE_SSL_CERT_CN: server
      APACHE_SSL_CERT: /server.crt
      APACHE_SSL_KEY: /server.key
      APACHE_LOGGING_PATH: /dev/null
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl.crt:/server.crt
      - ./ssl.key:/server.key
      - ./apache.sh:/entrypoint
      - server:/var/www/owncloud
    entrypoint: bash /entrypoint
    extra_hosts:
      - host.docker.internal:host-gateway
  oc10:
    image: owncloudci/core
    environment:
      PLUGIN_VERSION: 'latest'
      PLUGIN_CORE_PATH: /var/www/owncloud
    volumes:
      - server:/var/www/owncloud
      - ./entrypoint.sh:/entrypoint
    entrypoint: bash /entrypoint
    depends_on:
      - apache

volumes:
  server:
